"""不需要 GPU:PTX 助记符解析与按世代计数。`uv run pytest`。"""
from klab.harness.ptxdump import count, generations, mnemonics

# 手写的片段,覆盖三代指令 + 解析上的几个坑:谓词指令、标签、.directive、注释、缩进
PTX = """
//
// Generated by LLVM NVPTX Back-End
//
.version 8.4
.target sm_90a
.visible .entry matmul_kernel(
	.param .u64 matmul_kernel_param_0
)
{
	.reg .pred 	%p<3>;
$L__BB0_1:
	ld.global.v4.b32 	{%r1, %r2, %r3, %r4}, [ %rd7 + 0 ];
	@%p1 cp.async.cg.shared.global [ %r11 ], [ %rd12 ], 16;
	cp.async.commit_group ;
	cp.async.bulk.tensor.2d.shared::cluster.global.tile [%r20], [%rd30, {%r21, %r22}], [%r23];
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 {%r31,%r32,%r33,%r34}, [ %r35 ];
	mma.sync.aligned.m16n8k16.row.col.f32.bf16.bf16.f32 {%f1,%f2,%f3,%f4}, {%r1,%r2,%r3,%r4}, {%r5,%r6}, {%f1,%f2,%f3,%f4};
	mma.sync.aligned.m16n8k16.row.col.f32.bf16.bf16.f32 {%f5,%f6,%f7,%f8}, {%r1,%r2,%r3,%r4}, {%r7,%r8}, {%f5,%f6,%f7,%f8};
	wgmma.mma_async.sync.aligned.m64n256k16.f32.bf16.bf16 {%f9}, %rd40, %rd41, 1, 1, 1, 0, 0;
	bar.sync 	0;
	st.global.v2.b32 	[ %rd50 + 0 ], {%r60, %r61};
	ret;
}
"""


def test_mnemonics_strips_predicates_labels_and_directives():
    ms = list(mnemonics(PTX))
    assert "cp.async.cg.shared.global" in ms, "谓词指令 @%p1 前缀没剥掉"
    assert not any(m.startswith((".", "$", "//")) for m in ms), f"混进了指示符或标签:{ms}"


def test_longer_family_wins_so_tma_is_not_counted_as_ampere_cp_async():
    c = count(PTX)
    assert c["cp.async.bulk"] == 1          # Hopper TMA
    assert c["cp.async"] == 2               # Ampere 的 cp.async.cg + cp.async.commit_group,不含 bulk


def test_counts_per_generation_families():
    c = count(PTX)
    assert c["mma.sync"] == 2 and c["wgmma"] == 1 and c["ldmatrix"] == 1
    assert c["ld.global"] == 1 and c["st.global"] == 1 and c["bar.sync"] == 1


def test_generations_lists_hits_without_the_generic_bucket():
    assert generations(count(PTX)) == ["Hopper", "Ampere"]
    assert generations({"ld.global": 9, "fma": 3}) == []


def test_helper_instructions_do_not_claim_a_generation():
    """stmatrix / mbarrier / setmaxnreg 只是「某代起就有」的辅助指令,5090(sm_120)照样会发;
    它们出现不等于用上了那一代的核心能力,不能进判定 —— 实测 Triton 在 5090 上就发了 stmatrix。"""
    helpers_only = "\n".join([
        "\tstmatrix.sync.aligned.m8n8.x4.shared.b16 [ %r1 ], {%r2,%r3,%r4,%r5};",
        "\tmbarrier.arrive.shared.b64 %rd1, [ %r9 ];",
        "\tsetmaxnreg.dec.sync.aligned.u32 24;",
        "\tld.global.v4.b32 	{%r1, %r2, %r3, %r4}, [ %rd7 + 0 ];",
    ])
    c = count(helpers_only)
    assert c["stmatrix"] == 1 and c["mbarrier"] == 1 and c["setmaxnreg"] == 1
    assert generations(c) == [], "辅助指令不该让判定声称命中了某个世代"


def test_ampere_only_ptx_shows_no_hopper_or_blackwell():
    ampere = "\n".join(l for l in PTX.splitlines() if "wgmma" not in l and "cp.async.bulk" not in l)
    c = count(ampere)
    assert generations(c) == ["Ampere"]
    assert c.get("wgmma", 0) == 0 and c.get("tcgen05", 0) == 0


def test_wmma_counts_as_tensor_core_not_as_nothing():
    """nvcuda::wmma 在 PTX 里是 wmma.mma.sync,不是 mma.sync —— 初版指令表漏了这一族,
    导致手写 WMMA 的 kernel 被判成「没走 tensor core」。5090 实测 PTX 里就是这几条。"""
    ptx = "\n".join([
        "\twmma.load.a.sync.aligned.row.m16n16k16.bf16 {%r1,%r2,%r3,%r4}, [%rd5], 24;",
        "\twmma.load.b.sync.aligned.row.m16n16k16.bf16 {%r6,%r7,%r8,%r9}, [%rd10], 128;",
        "\twmma.mma.sync.aligned.row.row.m16n16k16.f32.bf16.bf16.f32 {%f1,%f2}, {%r1}, {%r6}, {%f1,%f2};",
        "\twmma.store.d.sync.aligned.row.m16n16k16.shared.f32 [%r20], {%f1,%f2}, 16;",
    ])
    c = count(ptx)
    assert c["wmma.mma"] == 1 and c["wmma.load"] == 2 and c["wmma.store"] == 1
    assert generations(c) == ["Ampere"], "WMMA 也是 tensor core,不能判成什么都没命中"
    assert c.get("wgmma", 0) == 0, "wmma 不能被算成 wgmma"
